# Generated by Django 2.2.10 on 2022-05-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=48)),
                ('collectioncode', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('public', models.BooleanField(null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpecifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='HigherTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('disciplin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('datetimecreated', models.DateTimeField(null=True)),
                ('datetimemodified', models.DateTimeField(null=True)),
                ('catalognr', models.CharField(blank=True, max_length=128, null=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('determination', models.CharField(blank=True, max_length=256, null=True)),
                ('broadgeography', models.CharField(blank=True, max_length=65536, null=True)),
                ('storage', models.CharField(blank=True, max_length=65536, null=True)),
                ('preptype', models.CharField(blank=True, max_length=256, null=True)),
                ('highertaxon', models.CharField(blank=True, max_length=256, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spwift.DataSet')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='spuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.SpecifyUser'),
        ),
        migrations.AddField(
            model_name='collection',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.Discipline'),
        ),
    ]
