# Generated by Django 2.2.10 on 2022-05-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatetime', models.DateTimeField()),
                ('csfrtoken', models.CharField(blank=True, max_length=64, null=True)),
                ('sessionid', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=8, null=True)),
                ('currentcollection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.Collection')),
                ('currentpreptype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.PreparationType')),
                ('spuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.SpecifyUser')),
            ],
        ),
    ]
