# Generated by Django 2.2.10 on 2022-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0002_auto_20220321_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifyuser',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specifyuser',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
