# Generated by Django 2.2.10 on 2022-05-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0003_auto_20220511_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highertaxon',
            old_name='disciplin',
            new_name='discipline',
        ),
    ]
