# Generated by Django 2.2.10 on 2022-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0005_auto_20220512_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
