# Generated by Django 2.2.10 on 2022-05-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0006_taxon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetrow',
            name='highertaxon',
        ),
        migrations.RemoveField(
            model_name='datasetrow',
            name='preptype',
        ),
    ]
