# Generated by Django 3.2.12 on 2022-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0006_auto_20220329_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationtype',
            name='sppreptypeid',
            field=models.IntegerField(null=True),
        ),
    ]
