# Generated by Django 2.2.10 on 2022-05-16 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0007_auto_20220516_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrow',
            name='highertaxon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.HigherTaxon'),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='highertaxonname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='preptype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.PreparationType'),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='preptypename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
