# Generated by Django 3.2.12 on 2022-03-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0008_auto_20220330_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.IntegerField(null=True)),
                ('datetimecreated', models.DateTimeField(null=True)),
                ('datetimemodified', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='spcollection',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='spcollection',
            name='spcollectionid',
            field=models.BigIntegerField(null=True),
        ),
    ]
