# Generated by Django 3.2.12 on 2022-03-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0009_auto_20220330_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcollection',
            name='spcollectionid',
        ),
    ]
