# Generated by Django 3.2.12 on 2022-04-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0011_dataset_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preparationtype',
            old_name='sppreptypeid',
            new_name='collectionid',
        ),
    ]
