# Generated by Django 3.2.12 on 2022-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0012_rename_sppreptypeid_preparationtype_collectionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
