# Generated by Django 3.2.12 on 2022-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0013_session_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrow',
            name='broadgeography',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='determination',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='storage',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
