# Generated by Django 3.2.12 on 2022-04-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0015_auto_20220407_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.spcollection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='spuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.specifyuser'),
        ),
        migrations.AlterField(
            model_name='preparationtype',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.spcollection'),
        ),
        migrations.AlterField(
            model_name='session',
            name='currentcollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.spcollection'),
        ),
        migrations.AlterField(
            model_name='session',
            name='currentpreptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.preparationtype'),
        ),
        migrations.AlterField(
            model_name='session',
            name='spuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spwift.specifyuser'),
        ),
    ]
