# Generated by Django 3.2.12 on 2022-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0016_auto_20220407_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrow',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='catalognr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
