# Generated by Django 3.2.12 on 2022-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwift', '0018_auto_20220407_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollObjectRecord',
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='name',
            field=models.CharField(default='datasetrowname', max_length=256),
            preserve_default=False,
        ),
    ]
